version: '3.3'
services: 


  cloud:
    build: ./cloudComputing
    ports:
      - "8081:8081"
    container_name: cloud
    environment: 
     - DATABASE_DOMAIN=postgres
     - USERNAME_POSTGRES=postgres
     - PASSWORD_POSTGRES=root
    links:
     - postgres

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cloud
    volumes:
      - database:/var/lib/postgresql/data

  nginx: 
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    links:
     - cloud

 


volumes:
  database: