version: '3.3'
services: 


  cloud:
#    build: ./cloudComputing
    image: damjanbanjac14/cloud_computing
    ports:
      - "8081:8081"
    container_name: cloud
    environment: 
     - DATABASE_DOMAIN=postgres
     - USERNAME_POSTGRES=postgres
     - PASSWORD_POSTGRES=root
     - POSTGRES_DB=cloud
     - HOST_APP=cloud
    links:
     - postgres
   
  cloud1:
    build: ./cloudComputing
    ports:
      - "8082:8081"
    container_name: cloud1
    environment: 
     - DATABASE_DOMAIN=postgres1
     - USERNAME_POSTGRES=postgres
     - PASSWORD_POSTGRES=root
     - POSTGRES_DB=cloud
     - HOST_APP=cloud1
    links:
     - postgres1

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cloud
    volumes:
      - database:/var/lib/postgresql/data
      
  postgres1:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    container_name: postgres1
    restart: always
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cloud
    volumes:
      - database1:/var/lib/postgresql/data

  nginx: 
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    links:
     - cloud
     
  nginx2:
    build: ./nginx/loadBalancer
    container_name: nginx1
    ports:
      - 81:80
    links:
      - cloud
      - cloud1


 


volumes:
  database:
  database1: